### ISSUE TITLE
aliases with environment variables

### ISSUE THREAD

**Issue by rickysarraf** [cykerway/complete-alias#20] opened 2021-04-08 07:45 UTC
First of all, thank you so much for your work. This is a very helpful tool you've created.

I have a bunch of aliases where I prepend it with a variable. Like the below:

```
alias researchut_dch='DEBEMAIL="ritesh.sarraf@researchut.com" DEBFULLNAME="Ritesh Raj Sarraf" dch --force-distribution -Dresearchut '
```

The bash auto-completion for such aliases does not work. Is it something that is a bug or a limitation ?

**Comment by cykerway** [comment] 2021-04-10 13:26
I don't have a Debian at hand so I tested with `systemctl` and it is working:

    alias researchut_dch='DEBEMAIL="ritesh.sarraf@researchut.com" DEBFULLNAME="Ritesh Raj Sarraf" systemctl --quiet '
    complete -F _complete_alias researchut_dch

Did you forget to set its completion function to `_complete_alias`?

**Comment by rickysarraf** [comment] 2021-04-12 14:15
I have checked to confirm that the settings were set proper. For your ease, and to make the example generic, I did this:

```
rrs@priyasi:~$ grep rrs_ls ~/.bash_aliases 
alias rrs_ls='HOME=/home/rrs ls '
19:24 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    

rrs@priyasi:~$ grep rrs_ls ~/.bash_completion
complete -F _complete_alias rrs_ls
19:24 ♒ ॐ ♅ ♄ ⛢     ☺ 😄    
```

Tabs don't work but if I explicitly specify the option to the alias, the correct help text from GNU Coreutils is displayed.

**Comment by cykerway** [comment] 2021-04-14 16:46
Don't test with config files. Type these commands in an interactive session to see if it works:

    $ alias rrs_ls='HOME=/home/rrs ls '
    $ complete -F _complete_alias rrs_ls

If it still doesn't work, report your output of these commands:

    $ bash --version
    $ alias | grep rrs_ls
    $ complete | grep rrs_ls

**Comment by rickysarraf** [comment] 2021-04-19 08:16
> complete -F _complete_alias rrs_ls

Sorry for the delay. Below is all the information you asked for. And yes, even after trying the commands in an interactive session, I see the same problem. No auto-completion.

```
rrs@priyasi:~/.../researchut-hugo (master)$ alias rrs_ls='HOME=/home/rrs ls '

rrs@priyasi:~/.../researchut-hugo (master)$ complete -F _complete_alias rrs_ls

rrs@priyasi:~/.../researchut-hugo (master)$ rrs_ls --^C

rrs@priyasi:~/.../researchut-hugo (master)$ bash --version
GNU bash, version 5.1.4(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

rrs@priyasi:~/.../researchut-hugo (master)$ alias | grep rrs_ls
alias rrs_ls='HOME=/home/rrs ls '

rrs@priyasi:~/.../researchut-hugo (master)$ complete | grep rrs_ls
complete -F _complete_alias rrs_ls

rrs@priyasi:~/.../researchut-hugo (master)$ 
```

**Comment by cykerway** [comment] 2021-04-27 07:59
I guess the problem is not related to the environment variable but the trailing blank. Are you able to reproduce the bug with:

    $ alias rrs_ls='ls '
    $ complete -F _complete_alias rrs_ls

and

    $ alias rrs_ls='ls '
    $ complete -F _complete_alias rrs_ls

Try both versions [1.9.0](https://github.com/cykerway/complete-alias/releases/tag/1.9.0) and [1.10.0](https://github.com/cykerway/complete-alias/releases/tag/1.10.0) then tell me which snippet works with which version?

**Comment by rickysarraf** [comment] 2021-04-27 16:18
> I guess the problem is not related to the environment variable but the trailing blank. Are you able to reproduce the bug with:
> 
> ```
> $ alias rrs_ls='ls '
> $ complete -F _complete_alias rrs_ls
> ```
> 
> and
> 
> ```
> $ alias rrs_ls='ls '
> $ complete -F _complete_alias rrs_ls
> ```
> 
> Try both versions [1.9.0](https://github.com/cykerway/complete-alias/releases/tag/1.9.0) and [1.10.0](https://github.com/cykerway/complete-alias/releases/tag/1.10.0) then tell me which snippet works with which version?

@cykerway Both the example snippets you shared look same to me. And I'm not sure which trailing blank you are referring to. Are you talking about the example I pasted above ? That trailing blank line is just because I formatted it.

**Comment by cykerway** [comment] 2021-04-28 01:39
Sorry, typo. I mean:

    $ alias rrs_ls='ls'
    $ complete -F _complete_alias rrs_ls

and

    $ alias rrs_ls='ls '
    $ complete -F _complete_alias rrs_ls

Now you see which trailing blank it is. If the second one works with 1.10.0 then your original example should also work with 1.10.0. Let me know if this is the case.

By the way, I guess your `ls` is also an alias to itself. Would you like to paste the alias body of your `ls` to help debug the problem?

    $ alias ls

**Comment by rickysarraf** [comment] 2021-04-29 10:40
@cykerway Thank you. Your latest `1.10.0`  version of the script fixes the problem. And yes. `ls` itself is an alias, which is commonly set on Debian based systems.

```
# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ] && [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto -F'
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

#
# Some more alias to avoid making mistakes:
alias rm='rm -i'
alias cp='cp -i --reflink=auto'
alias mv='mv -i'
alias vidir='vidir -v'
```

**Comment by cykerway** [comment] 2021-04-29 17:16
Great. Looks like the problem has been fixed. I'll close this ticket then.

**Closed by cykerway** 2021-04-29 17:16 UTC
